### ISSUE TITLE
Button placement in user of admin dashboard 

### ISSUE THREAD

**Issue by Rojenstha** [SachinGrg666/Dine-In#19]
The edit and delete button for user page has been misplaced, it should be side by side.
![IMG_20240517_230606_926.jpg](https://github.com/SachinGrg666/Dine-In/assets/119285275/3e38350c-f17e-4130-b0a7-80089b8bdaf2)

**Comment by BishnuKhadka722** [comment]
![user php](https://github.com/SachinGrg666/Dine-In/assets/119380563/2654f5b0-2a65-48db-8f5c-837dff4fb75f)
Fixed now
