### ISSUE TITLE
Action buttons in manage tables (admin dashboard)

### ISSUE THREAD

**Issue by Rojenstha** [SachinGrg666/Dine-In#20]
The action button for edit and deletion of the table has been similarly misplaced, should be side by side.
![IMG_20240517_230604_236.jpg](https://github.com/SachinGrg666/Dine-In/assets/119285275/157bf690-6222-41c6-a81b-995483e96f6a)

**Comment by BishnuKhadka722** [comment]
![manage-table php](https://github.com/SachinGrg666/Dine-In/assets/119380563/64e5a841-bfde-46ca-9ecb-6d5904d74617)
 
this issue is fixed now
